// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWPgiI5uxvEMhjuod5m2Er-or8hSS37AQ',
    appId: '1:167495836511:web:6a910ec3feeb6937288cea',
    messagingSenderId: '167495836511',
    projectId: 'rachadiaria',
    authDomain: 'rachadiaria.firebaseapp.com',
    storageBucket: 'rachadiaria.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWPgiI5uxvEMhjuod5m2Er-or8hSS37AQ',
    appId: '1:167495836511:android:YOUR_ANDROID_APP_ID',
    messagingSenderId: '167495836511',
    projectId: 'rachadiaria',
    storageBucket: 'rachadiaria.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWPgiI5uxvEMhjuod5m2Er-or8hSS37AQ',
    appId: '1:167495836511:ios:YOUR_IOS_APP_ID',
    messagingSenderId: '167495836511',
    projectId: 'rachadiaria',
    storageBucket: 'rachadiaria.firebasestorage.app',
    iosBundleId: 'com.example.rachaDiariaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWPgiI5uxvEMhjuod5m2Er-or8hSS37AQ',
    appId: '1:167495836511:ios:YOUR_MACOS_APP_ID',
    messagingSenderId: '167495836511',
    projectId: 'rachadiaria',
    storageBucket: 'rachadiaria.firebasestorage.app',
    iosBundleId: 'com.example.rachaDiariaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWPgiI5uxvEMhjuod5m2Er-or8hSS37AQ',
    appId: '1:167495836511:web:6a910ec3feeb6937288cea',
    messagingSenderId: '167495836511',
    projectId: 'rachadiaria',
    authDomain: 'rachadiaria.firebaseapp.com',
    storageBucket: 'rachadiaria.firebasestorage.app',
  );
}
